name: Build/release docker images and push
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and release docker images

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.event.repository.full_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.event.repository.full_name }}
  
  binary:
    runs-on: ubuntu-latest
    name: Build and release binary

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      
      - name: Build
        run: |
          make build
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Itachi"
          files: |
            ./itachi